version: '3'

networks:
  wordpress:

services:
  web:
    image: php:7.3-apache
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
      - 443:443
    links:
      - mysql
    networks:
      - wordpress

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - wordpress

volumes:
  mysql:
